routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\TagController;
use App\Http\Controllers\SizeController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\AboutController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\BrandController;
use App\Http\Controllers\ColorController;
use App\Http\Controllers\SlideController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\WebsiteController;
use App\Http\Controllers\CategoriController;
use App\Http\Controllers\SubCategoryController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__ . '/auth.php';



// Frontend view
Route::get('/', [WebsiteController::class, 'website']);
Route::get('/product-view/{id}', [WebsiteController::class, 'productview'])->name('product.details');
Route::get('/allproduct_cate/{id}', [WebsiteController::class, 'allproduct'])->name('product.cate');
Route::get('/allproduct_subcate/{id}', [WebsiteController::class, 'allproductsubcate'])->name('product.subcate');
Route::get('/allproduct_brand/{id}', [WebsiteController::class, 'allproductbrand'])->name('product.brand');
// All product route
Route::middleware('auth')->group(function () {
    Route::put('/index/{id}', [UserController::class, 'update'])->name('users.update');
    Route::get('/index/{id}/edit', [UserController::class, 'edit'])->name('users.edit');
    Route::get('/index', [UserController::class, 'index'])->name('users.index');
    Route::get('/role', [UserController::class, 'role'])->name('roles.index');


    Route::get('/profile', [UserController::class, 'profile'])->name('users.profile');
    Route::get('/admin', [AdminController::class, 'home'])->name('home');


    //All category route

    Route::get('/products', [ProductController::class, 'product'])->name('product.list');
    Route::get('/products/create', [ProductController::class, 'create'])->name('product.create');
    Route::post('/products', [ProductController::class, 'store'])->name('product.store');
    Route::get('/products/{product}/view', [ProductController::class, 'view'])->name('product.view');
    Route::delete('/products/{product}/delete', [ProductController::class, 'destroy'])->name('product.destroy');
    Route::get('/products/{product}/edit', [ProductController::class, 'edit'])->name('product.edit');
    Route::put('/products/{product}/update', [ProductController::class, 'update'])->name('product.update');

    //All category route

    Route::get('/categoris', [CategoriController::class, 'category'])->name('category.list');
    Route::get('/categoris/create', [CategoriController::class, 'create'])->name('category.create');
    Route::post('/categoris', [CategoriController::class, 'store'])->name('category.store');
    Route::get('/categoris/{categori}/edit', [CategoriController::class, 'edit'])->name('category.edit');
    Route::put('/categoris/{categori}/update', [CategoriController::class, 'update'])->name('category.update');
    Route::delete('/categoris/{categori}/delete', [CategoriController::class, 'destroy'])->name('category.destroy');

    // Sub category route
    Route::resource('sub_categories', SubCategoryController::class);

    // All size Route
    Route::resource('sizes', SizeController::class);

    //All Tag route
    Route::resource('tags', TagController::class);

    //All brand route
    Route::resource('brands', BrandController::class);

    //All color route
    Route::resource('colors', ColorController::class);
    //All color route
    Route::resource('abouts', AboutController::class);
});

app/Models/SubCategory.php
<?php

namespace App\Models;


use App\Models\Brand;
use App\Models\Categori;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class SubCategory extends Model
{
    use HasFactory;
    public $table = "sub_categories";
    protected $guarded = [];

    public function subcategory()
    {
        return $this->belongsTo(Categori::class,'category_id');
    }
    public function brands()
    {
        return $this->hasMany(Brand::class,'sub_category_id');
    }

}

app/Http/Controllers/SubCategoryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Categori;
use App\Models\SubCategory;
use Illuminate\Http\Request;

class SubCategoryController extends Controller
{

    public function index()
    {
        $subcategory = SubCategory::with('subcategory')->get();
        return view(
            'backend_pages.subcategory.list',
            compact('subcategory')
        );
    }


    public function create()
    {
        $categories = Categori::all();
        return view('backend_pages.subcategory.create', compact('categories'));
    }


    public function store(Request $request)
    {

        $request->validate([
            'name' => 'required|min:4|unique:sub_categories',
            'details' => 'required|min:5|max:1000'
        ]);
        SubCategory::create(
            [
                'category_id' => $request->category_id,
                'name' => $request->name,
                'details' => $request->details,
                'status' => $request->status ?? false

            ]
        );
        return redirect()->route('sub_categories.index')->with('message', 'Successfully Added  New Sub category');
    }



    public function edit(SubCategory $subCategory)
    {
        $categories = Categori::all();
        return view('backend_pages.subcategory.edit', compact('categories', 'subCategory'));
    }


    public function update(Request $request, SubCategory $subCategory)
    {
        $request->validate([
            'name' => 'required|min:4|unique:sub_categories',
            'details' => 'required|min:5|max:1000'
        ]);
        $subCategory->update(
            [
                'category_id' => $request->category_id,
                'name' => $request->name,
                'details' => $request->details,
                'status' => $request->status ?? false

            ]
        );
        return redirect()->route('sub_categories.index')->with('message', 'Successfully Update Sub category');
    }


    public function destroy(SubCategory $subCategory)
    {

        if ($subCategory) {
            $subCategory->delete();
            return redirect()->route('sub_categories.index')->with('message', 'Delete Successfully');
        } else {
            return redirect()->back();
        }
    }
}

resources/views/backend_pages/subcategory/create.blade.php
<x-backend.master>

    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-lg-8">
                <h4> New Sub Category</h4>


                <form method="POST" action="{{ route('sub_categories.store') }}" enctype="multipart/form-data">
                    @csrf
                    <div class="col-md-8">
                        <div class="form-group">

                            <label for="category">Category</label>

                            <select class="form-control" name="category_id" id="category">
                                <option>select one</option>
                                @foreach ($categories as $category)

                                    <option value="{{ $category->id }}">{{ $category->name }}</option>
                                @endforeach
                            </select>

                        </div>
                        <x-utility.from.input name="name" type="text" placeholder="Enter Category Name"
                            :value="old('name')" />

                        <x-utility.from.textarea name="details" :value="old('details')" />

                        <div class="form-check">
                            <input name="status" class="form-check-input" type="checkbox" value="1"
                                id="isActiveInput" checked>
                            <label class="form-check-label" for="isActiveInput">
                                Active Status
                            </label>
                        </div>
                    </div>

                    <br>
                    <div>
                        <button type="reset" class="btn btn-warning">Reset</button>
                        <button type="submit" class="btn btn-primary">Submit</button>

                    </div>

                </form>


            </div>
        </div>
    </div>



</x-backend.master>

resources/views/backend_pages/subcategory/edit.blade.php
<x-backend.master>
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-lg-8">
                <h4>Sub Category Update</h4>


                <form method="POST" action="{{ route('sub_categories.update', ['sub_category'=> $subCategory->id]) }}"
                    enctype="multipart/form-data">
                    @method('put')
                    @csrf
                    <div class="col-md-8">
                        <div class="form-group">

                            <label for="category">Category</label>

                            <select class="form-control" name="category_id" id="category" value="{{old('category_id')}}">
                                @foreach ($categories as $category)
                                    <option value="{{ $category->id }}">{{ $category->name }}</option>
                                @endforeach
                            </select>

                        </div>

                        <x-utility.from.input name="name" type="text" :value="old('name', $subCategory->name)" />
                        <x-utility.from.textarea name="details" :value="old('details', $subCategory->details)" />
                    </div>
                    <div class="form-check">
                        <input name="status" class="form-check-input" type="checkbox" value="1"
                            id="isActiveInput"{{ $subCategory->status ? 'checked' : '' }}>
                        <label class="form-check-label" for="isActiveInput">
                            Active Status
                        </label>
                    </div>

                    <br>
                    <button type="reset" class="btn btn-warning">Reset</button>

                    <button type="submit" class="btn btn-primary">Update</button>

                </form>


            </div>
        </div>
    </div>
</x-backend.master>

resources/views/backend_pages/subcategory/list.blade.php
<x-backend.master>
    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-table me-1"></i>
            Sub Category List
            <a class="btn btn-primary" href="{{ route('sub_categories.create') }}">Sub Category Add</a>
        </div>
        <x-utility.massage :message="session('message')" />
        <div class="card-body">
            <table id="datatablesSimple">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Name</th>
                        <th>Category</th>
                        <th>Details</th>
                        <th>Status</th>
                        <th>Edit</th>
                        <th>Delete</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($subcategory as $subcategory)
                        <tr>
                            <td>{{ $subcategory->id }}</td>
                            <td>{{ $subcategory->name }}</td>
                            <td>{{ $subcategory->subcategory->name }}</td>
                            <td>{{ $subcategory->details }}</td>
                            <td>{{ $subcategory->status }}</td>

                            <td>
                                <a class="btn btn-primary"
                                    href="{{ route('sub_categories.edit', ['sub_category' => $subcategory->id]) }}">Edit</a>
                            </td>
                            <td>
                                <form method="POST"
                                    action="{{ route('sub_categories.destroy', ['sub_category' => $subcategory->id]) }}">
                                    @csrf
                                    @method('delete')
                                    <button class="btn btn-danger"
                                        onclick="return confirm('Are you sure want to delete?')">Delete</button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
    @push('js')
        <script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" crossorigin="anonymous"></script>
        <script src="{{ asset('Backend') }}/js/datatables-simple-demo.js"></script>
    @endpush

</x-backend.master>