routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\TagController;
use App\Http\Controllers\SizeController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\AboutController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\BrandController;
use App\Http\Controllers\ColorController;
use App\Http\Controllers\SlideController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\WebsiteController;
use App\Http\Controllers\CategoriController;
use App\Http\Controllers\SubCategoryController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__ . '/auth.php';



// Frontend view
Route::get('/', [WebsiteController::class, 'website']);
Route::get('/product-view/{id}', [WebsiteController::class, 'productview'])->name('product.details');
Route::get('/allproduct_cate/{id}', [WebsiteController::class, 'allproduct'])->name('product.cate');
Route::get('/allproduct_subcate/{id}', [WebsiteController::class, 'allproductsubcate'])->name('product.subcate');
Route::get('/allproduct_brand/{id}', [WebsiteController::class, 'allproductbrand'])->name('product.brand');
// All product route
Route::middleware('auth')->group(function () {
    Route::put('/index/{id}', [UserController::class, 'update'])->name('users.update');
    Route::get('/index/{id}/edit', [UserController::class, 'edit'])->name('users.edit');
    Route::get('/index', [UserController::class, 'index'])->name('users.index');
    Route::get('/role', [UserController::class, 'role'])->name('roles.index');


    Route::get('/profile', [UserController::class, 'profile'])->name('users.profile');
    Route::get('/admin', [AdminController::class, 'home'])->name('home');


    //All category route

    Route::get('/products', [ProductController::class, 'product'])->name('product.list');
    Route::get('/products/create', [ProductController::class, 'create'])->name('product.create');
    Route::post('/products', [ProductController::class, 'store'])->name('product.store');
    Route::get('/products/{product}/view', [ProductController::class, 'view'])->name('product.view');
    Route::delete('/products/{product}/delete', [ProductController::class, 'destroy'])->name('product.destroy');
    Route::get('/products/{product}/edit', [ProductController::class, 'edit'])->name('product.edit');
    Route::put('/products/{product}/update', [ProductController::class, 'update'])->name('product.update');

    //All category route

    Route::get('/categoris', [CategoriController::class, 'category'])->name('category.list');
    Route::get('/categoris/create', [CategoriController::class, 'create'])->name('category.create');
    Route::post('/categoris', [CategoriController::class, 'store'])->name('category.store');
    Route::get('/categoris/{categori}/edit', [CategoriController::class, 'edit'])->name('category.edit');
    Route::put('/categoris/{categori}/update', [CategoriController::class, 'update'])->name('category.update');
    Route::delete('/categoris/{categori}/delete', [CategoriController::class, 'destroy'])->name('category.destroy');

    // Sub category route
    Route::resource('sub_categories', SubCategoryController::class);

    // All size Route
    Route::resource('sizes', SizeController::class);

    //All Tag route
    Route::resource('tags', TagController::class);

    //All brand route
    Route::resource('brands', BrandController::class);

    //All color route
    Route::resource('colors', ColorController::class);
    //All color route
    Route::resource('abouts', AboutController::class);
});

app/Models/Size.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Size extends Model
{
    use HasFactory;
    protected $guarded=[];
}

app/Http/Controllers/SizeController.php
<?php

namespace App\Http\Controllers;


use App\Http\Requests\SizeRequest;

use App\Models\Size;

class SizeController extends Controller
{
    public function index()
    {
        $size = Size::all();
        return view('backend_pages.size.list', compact('size'));
    }

    public function create()
    {
        return view('backend_pages.size.create');
    }

    public function store(SizeRequest $request)
    {
        $request->validate([
            'name' => 'required|unique:sizes|max:255',

        ]);
        Size::create([
            'name' => $request->name,
            'status' => $request->status ?? false
        ]);
        return redirect()->route('sizes.index')->with('message', 'Successfully Add  New Size');
    }



    public function edit(Size $size)
    {
        return view('backend_pages.size.edit', compact('size'));
    }


    public function update(SizeRequest $request, Size $size)
    {
        $request->validate([
            'name' => 'required|unique:sizes|max:255',

        ]);
        $size->update([
            'name' => $request->name,
            'status' => $request->status ?? false
        ]);
        return redirect()->route('sizes.index')->with('message', 'Successfully Update');
    }

    public function destroy(Size $size){
        if ($size) {
            $size->delete();
            return redirect()->route('sizes.index')->with('message', 'Delete Successfully' );


        } else {
            return redirect()->back();
        }
    }
}

resources/views/backend_pages/size/create.blade.php
<x-backend.master>

    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-lg-8">
                <h4> New Size Add</h4>
                <form method="POST" action="{{ route('sizes.store') }}" enctype="multipart/form-data">
                    @csrf
                    <div class="col-md-8">
                        <x-utility.from.input name="name" type="text"  placeholder="Enter size" :value="old('name')" />
                        <div class="form-check">
                            <input name="status" class="form-check-input" type="checkbox" value="1"
                                id="isActiveInput" checked>
                            <label class="form-check-label" for="isActiveInput">
                                Active Status
                            </label>
                        </div>
                    </div>
                    <br>
                    <button type="reset" class="btn btn-warning">Reset</button>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>

</x-backend.master>

resources/views/backend_pages/size/edit.blade.php
<x-backend.master>

    <div class="container m-5">
        <div class="row justify-content-center">
            <div class="col-lg-8">
                <h4>Size Update</h4>
                <form method="POST" action="{{route('sizes.update',['size'=>$size->id])}}" enctype="multipart/form-data">
                    @csrf
                    @method('put')
                    <div class="col-md-8">
                        <label for="size"class="col-form-label-lg ">Size</label>
                        <input name="name" type="text"
                            class="form-control @error('name') is-invalid @enderror"value="{{ old('name',$size->name) }}"
                            id="size" placeholder="Enter size">
                        <x-utility.errorfield name='name' />
                    </div>
                    <br>
                    <div class="form-check">
                        <input name="status" class="form-check-input" type="checkbox" value="1"
                            id="isActiveInput"{{ $size->status ? 'checked' : '' }}>
                        <label class="form-check-label" for="isActiveInput">
                            Active Status
                        </label>
                    </div>
                    <br>
                    <button type="reset" class="btn btn-warning">Reset</button>
                    <button type="submit" class="btn btn-primary">Update</button>
                </form>
            </div>
        </div>
    </div>

</x-backend.master>

resources/views/backend_pages/size/list.blade.php
<x-backend.master>
    <div class="card mb-4">

        <div class="card-header">
            <i class="fas fa-table me-1"></i>
            Size List
            <a class="btn btn-primary" href="{{route('sizes.create')}}">Size Add</a>
        </div>

        <x-utility.massage :message="session('message')" />

        <div class="card-body">
            <table id="datatablesSimple">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Title</th>
                        <th>Status</th>
                        <th>Edit</th>
                        <th>Delete</th>
                    </tr>
                </thead>
                <tbody>


                 @foreach ($size as $data )


                        <tr>
                            <td>{{$data->id}}</td>
                            <td>{{$data->name}}</td>

                            <td> {{$data->status }}   </td>
                            <td>
                                <a class="btn btn-primary" href="{{route('sizes.edit',['size'=>$data->id])}}">Edit</a>
                            </td>
                            <td>
                                <form method="POST" action="{{route('sizes.destroy',['size'=>$data->id])}}">
                                    @csrf
                                    @method('delete')
                                    <button class="btn btn-danger"
                                        onclick="return confirm('Are you sure want to delete?')">Delete</button>
                                </form>

                            </td>
                        </tr>
                        @endforeach
                </tbody>
            </table>
        </div>
    </div>
    @push('js')
        <script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" crossorigin="anonymous"></script>
        <script src="{{ asset('Backend') }}/js/datatables-simple-demo.js"></script>
    @endpush

</x-backend.master>