routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\TagController;
use App\Http\Controllers\SizeController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\AboutController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\BrandController;
use App\Http\Controllers\ColorController;
use App\Http\Controllers\SlideController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\WebsiteController;
use App\Http\Controllers\CategoriController;
use App\Http\Controllers\SubCategoryController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__ . '/auth.php';



// Frontend view
Route::get('/', [WebsiteController::class, 'website']);
Route::get('/product-view/{id}', [WebsiteController::class, 'productview'])->name('product.details');
Route::get('/allproduct_cate/{id}', [WebsiteController::class, 'allproduct'])->name('product.cate');
Route::get('/allproduct_subcate/{id}', [WebsiteController::class, 'allproductsubcate'])->name('product.subcate');
Route::get('/allproduct_brand/{id}', [WebsiteController::class, 'allproductbrand'])->name('product.brand');
// All product route
Route::middleware('auth')->group(function () {
    Route::put('/index/{id}', [UserController::class, 'update'])->name('users.update');
    Route::get('/index/{id}/edit', [UserController::class, 'edit'])->name('users.edit');
    Route::get('/index', [UserController::class, 'index'])->name('users.index');
    Route::get('/role', [UserController::class, 'role'])->name('roles.index');


    Route::get('/profile', [UserController::class, 'profile'])->name('users.profile');
    Route::get('/admin', [AdminController::class, 'home'])->name('home');


    //All category route

    Route::get('/products', [ProductController::class, 'product'])->name('product.list');
    Route::get('/products/create', [ProductController::class, 'create'])->name('product.create');
    Route::post('/products', [ProductController::class, 'store'])->name('product.store');
    Route::get('/products/{product}/view', [ProductController::class, 'view'])->name('product.view');
    Route::delete('/products/{product}/delete', [ProductController::class, 'destroy'])->name('product.destroy');
    Route::get('/products/{product}/edit', [ProductController::class, 'edit'])->name('product.edit');
    Route::put('/products/{product}/update', [ProductController::class, 'update'])->name('product.update');

    //All category route

    Route::get('/categoris', [CategoriController::class, 'category'])->name('category.list');
    Route::get('/categoris/create', [CategoriController::class, 'create'])->name('category.create');
    Route::post('/categoris', [CategoriController::class, 'store'])->name('category.store');
    Route::get('/categoris/{categori}/edit', [CategoriController::class, 'edit'])->name('category.edit');
    Route::put('/categoris/{categori}/update', [CategoriController::class, 'update'])->name('category.update');
    Route::delete('/categoris/{categori}/delete', [CategoriController::class, 'destroy'])->name('category.destroy');

    // Sub category route
    Route::resource('sub_categories', SubCategoryController::class);

    // All size Route
    Route::resource('sizes', SizeController::class);

    //All Tag route
    Route::resource('tags', TagController::class);

    //All brand route
    Route::resource('brands', BrandController::class);

    //All color route
    Route::resource('colors', ColorController::class);
    //All color route
    Route::resource('abouts', AboutController::class);
});

app/Models/Tag.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    use HasFactory;
    protected $guarded=[];
}

app/Http/Controllers/TagController.php
<?php

namespace App\Http\Controllers;

use App\Models\Tag;
use Illuminate\Http\Request;

class TagController extends Controller
{
   public function index(){
          $tag=Tag::all();
    return view('backend_pages.tag.list',compact('tag'));
   }

   public function create(){
    return view('backend_pages.tag.create');
   }

   public function store(Request $request){
// dd($request->all());
    $request->validate([
        'tag' => 'required|unique:tags|max:255',

    ]);
    Tag::create([
        'tag'=>$request->tag,
        'status' => $request->status ?? false
    ]);
    return redirect()->route('tags.index')->with('message', 'Successfully Add  New Tag');
   }


   public function edit(Tag $tag){
    return view('backend_pages.tag.edit',compact('tag'));
   }

   public function update(Request $request, Tag $tag){
    $request->validate([
        'tag' => 'required|unique:tags|max:255',

    ]);
    $tag->update([
        'tag'=>$request->tag,
        'status' => $request->status ?? false
    ]);
    return redirect()->route('tags.index')->with('message', 'Successfully update');
   }

   public function destroy(Tag $tag){
    if ($tag) {
        $tag->delete();
        return redirect()->route('tags.index')->with('message', 'Delete Successfully' );


    } else {
        return redirect()->back();
    }
   }

}

resources/views/backend_pages/tag/create.blade.php
<x-backend.master>

    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-lg-8">
                <h4> New Tag Add</h4>
                <form method="POST" action="{{route('tags.store')}}" enctype="multipart/form-data">
                    @csrf
                    <div class="col-md-8">
                        <x-utility.from.input name="tag" type="text" placeholder="Enter tag"
                            :value="old('tag')" />
                            <div class="form-check">
                                <input name="status" class="form-check-input" type="checkbox" value="1"
                                    id="isActiveInput" checked>
                                <label class="form-check-label" for="isActiveInput">
                                    Active Status
                                </label>
                            </div>

                    </div>
                    <br>
                    <button type="reset" class="btn btn-warning">Reset</button>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>

</x-backend.master>

resources/views/backend_pages/tag/edit.blade.php
<x-backend.master>

    <div class="container m-5">
        <div class="row justify-content-center">
            <div class="col-lg-8">
                <h4>Tag Upadte</h4>
                <form method="POST" action="{{route('tags.update',['tag'=>$tag->id])}}" enctype="multipart/form-data">
                    @csrf
                    @method('put')
                    <div class="col-md-8">

                        <label for="tag"class="col-form-label-lg ">Tag </label>
                        <input name="tag" type="text"
                            class="form-control @error('tag') is-invalid @enderror"value="{{ old('tag',$tag->tag) }}"
                            id="tag" placeholder="Enter tag">
                        <x-utility.errorfield name='tag' />
                    </div>
                    <br>
                    <div class="form-check">
                        <input name="status" class="form-check-input" type="checkbox" value="1"
                            id="isActiveInput"{{ $tag->tag ? 'checked' : '' }}>
                        <label class="form-check-label" for="isActiveInput">
                            Active Status
                        </label>
                    </div>
                    <br>
                    <button type="reset" class="btn btn-warning">reset</button>
                    <button type="submit" class="btn btn-primary">Update</button>
                </form>
            </div>
        </div>
    </div>

</x-backend.master>

resources/views/backend_pages/tag/list.blade.php
<x-backend.master>
    <div class="card mb-4">

        <div class="card-header">
            <i class="fas fa-table me-1"></i>
            Product List
            <a class="btn btn-primary" href="{{ route('tags.create') }}">Tag Add</a>
        </div>

        <x-utility.massage :message="session('message')" />

        <div class="card-body">
            <table id="datatablesSimple">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Title</th>
                        <th>Status</th>
                        <th>Edit</th>
                        <th>Delete</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($tag as $tag)
                        <tr>
                            <td>{{$tag->id}}</td>
                            <td>{{$tag->tag}}</td>
                            <td>{{$tag->status}}</td>
                            <td>
                                <a class="btn btn-primary" href="{{route('tags.edit',['tag'=>$tag->id])}}">Edit</a>
                            </td>
                            <td>
                                <form method="POST" action="{{route('tags.destroy',['tag'=>$tag->id])}}">
                                    @csrf
                                    @method('delete')
                                    <button class="btn btn-danger"
                                        onclick="return confirm('Are you sure want to delete?')">Delete</button>
                                </form>

                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
    @push('js')
        <script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" crossorigin="anonymous"></script>
        <script src="{{ asset('Backend') }}/js/datatables-simple-demo.js"></script>
    @endpush

</x-backend.master>